### ISSUE TITLE
GRPC server fails to start or serve responses

### ISSUE THREAD

**Issue by d1820** [testinggospels/camouflage#174]
Can not connect to the server instance and actually get a response. From bloom i get ```"2 UNKNOWN: Stream removed"``` from services calling container to container i get 
```json
{"@t":"2022-03-09T15:50:14.8670483Z","@m":"Call failed with gRPC error status. Status code: 'Unavailable', Message: '\"Error starting gRPC call. HttpRequestException: Connection refused (camouflage.svc.cluster.local:5057) SocketException: Connection refused\"'.","@i":"bcfa385f","StatusCode":"Unavailable","StatusMessage":"Error starting gRPC call. HttpRequestException: Connection refused (camouflage.svc.cluster.local:5057) SocketException: Connection refused","EventId":{"Id":3,"Name":"GrpcStatusError"},"SourceContext":"Grpc.Net.Client.Internal.GrpcCall","GrpcMethodType":"Unary","GrpcUri":"/KBX.CRE.ReferenceData.Contracts.v1.Services.ChargeTypeGrpcService/GetChargeTypeByCode","RequestId":"0HMG1SHRNUFVR:00000001","RequestPath":"/KBX.CRE.RateManagement.Contracts.v1.Services.RateGrpcService/CreateRates","ConnectionId":"0HMG1SHRNUFVR"}
```

I was hoping the log would give more insight. If i remove the mock server and point back to another container with the live service all is fine. I was thinking this could be related to how .netcore handles GRPC calls with the client vs other clients.

Url used in .net for connecting is ``` "http://camouflage.svc.cluster.local:5057"```

2. Folder Structure `....`
![image](https://user-images.githubusercontent.com/377631/157670978-5582af3e-5fda-4d67-8657-77722a213c1b.png)
![image](https://user-images.githubusercontent.com/377631/157671029-c657adc1-1f59-417e-a50e-e6e9e3ab6598.png)

3. Proto
```txt
syntax = "proto3";
package KBX.CRE.ReferenceData.Contracts.v1.Services;
import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

message ChargeType {
   string ChargeTypeId = 1;
   string TenantId = 2;
   string ChargeTypeCode = 3;
   string ChargeTypeDesc = 4;
   string CreateBy = 5;
   .google.protobuf.Timestamp CreateDateTime = 6;
   string LastChangeBy = 7;
   .google.protobuf.Timestamp LastChangeDateTime = 8;
   .google.protobuf.Timestamp RowVersion = 9;
}

message ChargeTypeQueryByCodeRequest {
   string ChargeType = 1;
}

message Error {
   int32 ErrorCode = 1;
   string Message = 2;
   string Domain = 3;
   map<string,string> MetaData = 4;
   int32 RetryDelayInMs = 5;
}

message GrpcChargeTypeListResponse {
   StatusCode Status = 1;
   bool HasError = 2;
   Error Error = 3;
   repeated ChargeType Result = 4;
}
message GrpcChargeTypeResponse {
   StatusCode Status = 1;
   bool HasError = 2;
   Error Error = 3;
   ChargeType Result = 4;
}
enum StatusCode {
   OK = 0;
   Cancelled = 1;
   Unknown = 2;
   InvalidArgument = 3;
   DeadlineExceeded = 4;
   NotFound = 5;
   AlreadyExists = 6;
   PermissionDenied = 7;
   Unauthenticated = 16;
   ResourceExhausted = 8;
   FailedPrecondition = 9;
   Aborted = 10;
   OutOfRange = 11;
   Unimplemented = 12;
   Internal = 13;
   Unavailable = 14;
   DataLoss = 15;
}
service ChargeTypeGrpcService {
   rpc GetChargeTypeByCode (ChargeTypeQueryByCodeRequest) returns (GrpcChargeTypeResponse);
}

```

MOCK
```json
{"Status":0,"HasError":false,"Error":null,"Result":{"ChargeTypeId":"3b624fea-590c-4594-b674-990076a17598","TenantId":"11111","ChargeTypeCode":"LH","ChargeTypeDesc":"LINE HAUL","CreateBy":"user","CreateDateTime":"2021-05-12T20:47:08.089927Z","LastChangeBy":"user","LastChangeDateTime":"2021-05-12T20:47:08.089927Z","RowVersion":"2021-05-12T20:47:08.089963Z"}}
```

YAML
```yaml
version: '3.4'

volumes:
  camouflage_data: {}

services:
  camouflage_ui:
    image: shubhendumadhukar/camouflage-filemanager:latest
    container_name: camouflage_ui
    volumes:
      - camouflage_data:/opt/virtual_services
    environment:
      FS_ROOT: /opt/virtual_services
      WRITE_PROTECTED: "false"
      PORT: 3001
    ports:
      - "3001:3001"
    labels:
      org.label-schema.group: "camouflage"
  camouflage:
    image: shubhendumadhukar/camouflage:latest
    container_name: camouflage
    hostname: camouflage.svc.cluster.local
    volumes:
      - camouflage_data:/app
    restart: unless-stopped
    ports:
      - "5057:5057"
      - "5051:5051"
      - "5555:5555"
    labels:
      org.label-schema.group: "camouflage"
networks:
  default:
    name: nat
```

**Expected behavior**

**Screenshots**
BLOOMRPC
![image](https://user-images.githubusercontent.com/377631/157670619-e1acb78b-be18-4233-8252-8f186e73388e.png)
DOCKER LOGS
![image](https://user-images.githubusercontent.com/377631/157670674-7018d7e9-b253-4783-aea7-ce299be7cccf.png)

**Desktop (please complete the following information):**
 - Windows
 - Docker Image
![image](https://user-images.githubusercontent.com/377631/157670794-52a1da1b-f22c-4005-a850-3d72d8134d65.png)

**Additional context**
[camouflage.log](https://github.com/testinggospels/camouflage/files/8223764/camouflage.log)

Attach camouflage.log file
