### ISSUE TITLE
Schema validation

### ISSUE THREAD

**Issue by richardruiter** [testinggospels/camouflage#195]
### Discussed in https://github.com/testinggospels/camouflage/discussions/194

<div type='discussions-op-text'>

<sup>Originally posted by **richardruiter** October 23, 2022</sup>
Hi, we are implementing Contract Testing and have a need for validating the mocks we create against OpenApi and XML-RPC schemas from the backend teams. This makes sure we don't make false assumptions when using a mock server.

We already have a homegrown mockserver with this principle baked in, but we need more functionality and camouflage covers it.
First I was thinking to create middleware that can be shared with multiple teams and created a successful PoC with `middleware.js`

However then the idea arose to make schema validation part of camouflage server.

```
loglevel: info
protocols:
  http:
    enable: true
    mocks_dir: "./mocks"
    port: 8080
validation:
  schemas:
    - https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.json
    - https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/example2.json
```

In the case of OpenApi It would parse the schemas with `@apidevtools/swagger-parser`, validate the request with `openapi-request-validator` and response with `openapi-response-validator.
</div>
